version: "3"

services:
  bluestar:
    build:
      context: .
      args:
        BASE_URL: "http://localhost:3001"
    image: ghcr.io/rasliche/bluestar-nuxt:1.0.0
    restart: always
    ports:
      - "3000:80"
    networks: 
      - bluestar-net
    environment:
      BASE_URL: "http://localhost:3001"
    restart: unless-stopped
    depends_on:
      - mongo_db

  bluestar_server:
    build: ./server
    image: ghcr.io/rasliche/bluestar-nuxt-server:1.0.0
    restart: always
    ports:
      - "3001:3001"
    command:
      "npm start"
    networks: 
      - bluestar-net
    environment:
      # Change username and password to db user and password
      MONGO_URI: "mongodb://bluestar:example@mongo_db:27017/bluestar"
      CLIENT_URL: "http://localhost:3000"
    restart: unless-stopped
    depends_on:
      - mongo_db

  mongo_db:
    image: mongo
    restart: always
    environment:
      # TODO: Use secrets instead of this...
      # CHANGE THESE!!!
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: bluestar
      MONGO_INITDB_USERNAME: bluestar
      MONGO_INITDB_PASSWORD: example
    networks:
      - bluestar-net
    volumes:
      - ./docker-mongo-init.sh:/docker-entrypoint-initdb.d/init-mongo.sh

networks:
  bluestar-net:
